name: gitleaks-scan

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup Gitleaks
      run: |
        brew install gitleaks
    
    - name: Secret Scan
      id: secretscan
      run: |
        gitleaks detect -s ${{github.workspace}} -r output.csv -f csv
      continue-on-error: true
    
    - name: Check file content
      id: report
      run: |
       if [ -s output.csv ]; then
         echo "::set-output name=secrets::1"
       else
         echo "No Secrets or credentials were found"
       fi
    
    - name: Upload Artifacts
      if: ${{steps.report.outputs.secrets}}
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: scan-report
        path: output.csv
    
    - name: Fail action
      if: ${{steps.report.outputs.secrets}} 
      run: |
        exit 1
