name: Java CI JF
on:
  
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_APIKEY }}
    - run: |
        jfrog rt ping
    - run: |
         jfrog rt dl artifacts/
         jfrog rt u aether artifacts/
         jfrog rt bp
    
         
